<a href="https://colab.research.google.com/github/darynabozhok/ML_course/blob/main/DB_HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [ ]:
import numpy as np

In [ ]:
vector = np.random.rand(10)


matrix = np.array([[11, 14, 17],
                   [20, 23, 26],
                   [29, 32, 35]])

print("Вектор:")
print(vector, "\n")
print(f"Розмір вектору: {vector.shape}")
print("\nМатриця:")
print(matrix, "\n")
print(f"Розмір матриці: {matrix.shape}")

Вектор:
[0.27755053 0.93380016 0.44765683 0.49988721 0.67509704 0.12370637
 0.22019123 0.67820425 0.83641925 0.35067123] 

Розмір вектору: (10,)

Матриця:
[[11 14 17]
 [20 23 26]
 [29 32 35]] 

Розмір матриці: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [ ]:
vector_new = vector + 10

print("Вектор:")
print(np.round(vector_new, 2), "\n")

Вектор:
[10.28 10.93 10.45 10.5  10.68 10.12 10.22 10.68 10.84 10.35] 



In [ ]:
matrix2 = matrix * 2

print("Матриця * 2:")
print(matrix2, "\n")


Матриця * 2:
[[22 28 34]
 [40 46 52]
 [58 64 70]] 



In [ ]:
#варіант 1
vector_2 = vector ** 2

print("Вектор в квадраті:")
print(np.round(vector_2, 2), "\n")

Вектор в квадраті:
[0.08 0.87 0.2  0.25 0.46 0.02 0.05 0.46 0.7  0.12] 



In [ ]:
#варіант 2
vector_2ex = np.square(vector)

print("Вектор в квадраті:")
print(np.round(vector_2ex, 2), "\n")

Вектор в квадраті:
[0.08 0.87 0.2  0.25 0.46 0.02 0.05 0.46 0.7  0.12] 




### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [ ]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [ ]:
result_matrix = np.dot(B, A)

print("\nМатриця:")
print(result_matrix, "\n")
print(f"Розмір матриці: {result_matrix.shape}")


Матриця:
[[0.7281 0.5202]
 [0.2034 0.2846]] 

Розмір матриці: (2, 2)


In [ ]:
result_vector = np.dot(result_matrix, C)

print("Вектор:")
print(result_vector, "\n")
print(f"Розмір вектору: {result_vector.shape}")

Вектор:
[[0.5202]
 [0.2846]] 

Розмір вектору: (2, 1)


In [ ]:
result = np.dot(result_matrix, D)

print("\nМатриця:")
print(result, "\n")
print(f"Розмір матриці: {result.shape}")


Матриця:
[[0.5202 0.7281]
 [0.2846 0.2034]] 

Розмір матриці: (2, 2)



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [ ]:
T_result_matrix = result_matrix.T

print("\nТранспонована матриця:")
print(T_result_matrix, "\n")
print(f"Розмір матриці: {T_result_matrix.shape}")


Транспонована матриця:
[[0.7281 0.2034]
 [0.5202 0.2846]] 

Розмір матриці: (2, 2)


In [ ]:
T_vector = vector.T


print("\nВектор:")
print(vector, "\n")
print(f"Розмір вектора: {vector.shape}")

print("\nТранспонований вектор:")
print(T_vector, "\n")
print(f"Розмір вектора: {T_vector.shape}")


Вектор:
[0.27755053 0.93380016 0.44765683 0.49988721 0.67509704 0.12370637
 0.22019123 0.67820425 0.83641925 0.35067123] 

Розмір вектора: (10,)

Транспонований вектор:
[0.27755053 0.93380016 0.44765683 0.49988721 0.67509704 0.12370637
 0.22019123 0.67820425 0.83641925 0.35067123] 

Розмір вектора: (10,)


вектор не змінився

In [ ]:
column_vector = np.expand_dims(vector, axis=1)

print("\nВектор-стовпчик:")
print(column_vector, "\n")
print(f"Розмір вектора-стовпчика: {column_vector.shape}")


print("\nВектор:")
print(vector, "\n")
print(f"Розмір вектора: {vector.shape}")




Вектор-стовпчик:
[[0.27755053]
 [0.93380016]
 [0.44765683]
 [0.49988721]
 [0.67509704]
 [0.12370637]
 [0.22019123]
 [0.67820425]
 [0.83641925]
 [0.35067123]] 

Розмір вектора-стовпчика: (10, 1)

Вектор:
[0.27755053 0.93380016 0.44765683 0.49988721 0.67509704 0.12370637
 0.22019123 0.67820425 0.83641925 0.35067123] 

Розмір вектора: (10,)


За допомогою операції numpy.expand_dims отримали вектор-стовпчик. vector початковий є вектором-рядком.



In [ ]:
T_column_vector = column_vector.T

print("\nТранспонований вектор:")
print(T_column_vector, "\n")
print(f"Розмір вектора: {T_column_vector.shape}")


Транспонований вектор:
[[0.27755053 0.93380016 0.44765683 0.49988721 0.67509704 0.12370637
  0.22019123 0.67820425 0.83641925 0.35067123]] 

Розмір вектора: (1, 10)


після транспонування вектор-стовпчик став вектором-рядком